title: "Rayyan Ahmed — Data Science"
description: ""
baseurl: "/RayyanAhmed.github.io"
url: "https://rayyanahmed105.github.io"
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Rayyan Ahmed"
github_username: "rayyanAhmed105"
medium_username: "RayyanElfadel"
exclude:
  - "README.md"
