title: "Rayyan Ahmed — Data Science"
description: "Production-like data engineering builds, explained clearly."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Rayyan Ahmmed"
github_username: "rayyanAhmed105"
medium_username: "RayyanElfadel"
exclude:
  - "README.md"
